name: Python App Integration
on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Doc generation
        run: scripts/mkdoc.sh

      - name: Run tests
        run: scripts/mktest.sh
  
  second_job:
    needs: build
    if: github.env == 0
    runs-on: ubuntu-latest

    steps: 
      - name: Print Hello World
        run: echo "Hello World"